server:
  port: 8880
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000